###################################################
#                                                 #
# Create VMware Guest                             #
#                                                 #
# Ansible Playbook to create a virtual machine    #
# on a VMware ESXI Host/Cluster                   #
#                                                 #
###################################################
---
- name: Create VMware Guest                               # Script Name
  hosts: vmware                                           # Hosts
  connection: local                                       # Connection
  gather_facts: false                                     # Gather facts?
  vars_prompt:                                            # Input from user
    - name: "vsphere_hostname"                            # Hostname of the vSphere Server (IP or FQDN)
      prompt: "vSphere Hostname"                          # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "vsphere_username"                            # Username to log in to vSphere as
      prompt: "vSphere Username"                          # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "vsphere_password"                            # Password for vSphere Username
      prompt: "vSphere Password"                          # The prompt the user sees
      private: yes                                        # Do NOT show the users input while typing
    - name: "guest_name"                                  # The name to use for the guest we are launching
      prompt: "Guest Name"                                # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "guest_disk_size"                             # Guests disk size in GB
      prompt: "Disk Size (GB)"                            # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "guest_datastore"                             # Name of the Datastore to store the VMDK
      prompt: "Guest Datastore"                           # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "guest_memory_size"                           # Guests memory size in MB
      prompt: "Memory Size (MB)"                          # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "guest_cpus"                                  # Number of CPU's for the guest
      prompt: "Number of CPUs"                            # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "guest_osid"                                  # Guest OSID (See below for options)
      prompt: "Guest OS"                                  # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "esxi_datacenter"                             # DataCenter where the ESXi host resides (ha-datacenter for non-clusters)
      prompt: "ESXi DataCenter Name"                      # The prompt the user sees
      private: no                                         # Show the users input while typing
    - name: "esxi_hostname"                               # Hostname of the ESXi host where the guest will be deployed
      prompt: "ESXi Hostname"                             # The prompt the user sees
      private: no                                         # Show the users input while typing
  tasks:                                                  # Tasks for Ansible to run
    - name: Create VMware Guest from Template             # Name of the Task
      vsphere_guest:                                      # Task to run
        validate_certs: no                                # Do NOT validate SSL Certificates
        vcenter_hostname: "{{ vsphere_hostname }}"        # vCenter Hostname from user input
        username: "{{ vsphere_username }}"                # vCenter Username from user input
        password: "{{ vsphere_password }}"                # vCenter Password from user input
        guest: "{{ guest_name }}"                         # vCenter Guest Name from user input
        state: powered_on                                 # vCenter Guest after creation
        vm_extra_config:                                  # A key, value pair of any extra values you want set or changed in the vmx file of the VM
          vcpu.hotadd: yes                                # Allow CPU's to be added without guest restart
          mem.hotadd: yes                                 # Allow memory to be added without guest restart
        vm_disk:                                          # Guest Virtual Disks
          disk1:                                          # Guest Primary Virtual Disk
            size_gb: "{{ guest_disk_size }}"              # Primary VMDK Size
            type: thin                                    # VMDK Provisioning Type
            datastore: "{{ guest_datastore }}"            # Datastore for VMDK
        vm_nic:                                           # Guest Network Interfaces
          nic1:                                           # Guest Primary Network Interface
            type: vmxnet3                                 # Network Interface Type
            network: VM Network                           # Network Interface Network
            network_type: standard                        # Network Type
        vm_hardware:                                      # Guest Hardware Profile
          memory_mb: "{{ guest_memory_size }}"            # Guest Memory Size from user input
          num_cpus: "{{ guest_cpus }}"                    # Guest Number of CPU's from user input
          osid: "{{ guest_osid }}"                        # Guest Operating System ID from user input (see below)
          scsi: paravirtual                               # Guest SCSI Type
        esxi:                                             # ESXi information
          datacenter: "{{ esxi_datacenter }}"             # ESXi DataCenter Name from user input
          hostname: "{{ esxi_hostname }}"                 # ESXi Hostname from user input

########## Guest Operating System ID's ESXi 6.5 ##########
#  Linux
#    asianux3Guest - Asianux 3 (32-bit)
#    asianux3_64Guest - Asianux 3 (64-bit)
#    asianux4Guest - Asianux 4 (32-bit)
#    asianux4_64Guest - Asianux 4 (64-bit)
#    asianux7_64Guest - Asianux 7 (64-bit)
#    centosGuest - CentOS 4/5 or later (32-bit)
#    centos64Guest - CentOS 4/5 or later (64-bit)
#    centos6Guest - CentOS 6 (32-bit)
#    centos6_64Guest - CentOS 6 (64-bit)
#    centos7_64Guest - CentOS 7 (64-bit)
#    coreos64Guest - CoreOS Linux (64-bit)
#    debian10Guest - Debian GNU/Linux 10 (32-bit)
#    debian10_64Guest - Debian GNU/Linux 10 (64-bit)
#    debian4Guest - Debian GNU/Linux 4 (32-bit)
#    debian4_64Guest - Debian GNU/Linux 4 (64-bit)
#    debian5Guest - Debian GNU/Linux 5 (32-bit)
#    debian5_64Guest - Debian GNU/Linux 5 (64-bit)
#    debian6Guest - Debian GNU/Linux 6 (32-bit)
#    debian6_64Guest - Debian GNU/Linux 6 (64-bit)
#    debian7Guest - Debian GNU/Linux 7 (32-bit)
#    debian7_64Guest - Debian GNU/Linux 7 (64-bit)
#    debian8Guest - Debian GNU/Linux 8 (32-bit)
#    debian8_64Guest - Debian GNU/Linux 8 (64-bit)
#    debian9Guest - Debian GNU/Linux 9 (32-bit)
#    debian9_64Guest - Debian GNU/Linux 9 (64-bit)
#    oesGuest - Novell Open Enterprise Server
#    oracleLinuxGuest - Oracle Linux 4/5 or later (32-bit)
#    oracleLinux64Guest - Oracle Linux 4/5 or later (64-bit)
#    oracleLinux6Guest - Oracle Linux 6 (32-bit)
#    oracleLinux6_64Guest - Oracle Linux 6 (64-bit)
#    oracleLinux7_64Guest - Oracle Linux 7 (64-bit)
#    other24xLinuxGuest - Other 2.4.x Linux (32-bit)
#    other24xLinux64Guest - Other 2.4.x Linux (64-bit)
#    other26xLinuxGuest - Other 2.6.x Linux (32-bit)
#    other26xLinux64Guest - Other 2.6.x Linux (64-bit)
#    other3xLinuxGuest - Other 3.x or later Linux (32-bit)
#    other3xLinux64Guest - Other 3.x or later Linux (64-bit)
#    otherLinuxGuest - Other Linux (32-bit)
#    otherLinux64Guest - Other Linux (64-bit)
#    rhel2Guest - Red Hat Enterprise Linux 2.1
#    rhel3Guest - Red Hat Enterprise Linux 3 (32-bit)
#    rhel3_64Guest - Red Hat Enterprise Linux 3 (64-bit)
#    rhel4Guest - Red Hat Enterprise Linux 4 (32-bit)
#    rhel4_64Guest - Red Hat Enterprise Linux 4 (64-bit)
#    rhel5Guest - Red Hat Enterprise Linux 5 (32-bit)
#    rhel5_64Guest - Red Hat Enterprise Linux 5 (64-bit)
#    rhel6Guest - Red Hat Enterprise Linux 6 (32-bit)
#    rhel6_64Guest - Red Hat Enterprise Linux 6 (64-bit)
#    rhel7_64Guest - Red Hat Enterprise Linux 7 (64-bit)
#    fedoraGuest - Red Hat Fedora (32-bit)
#    fedora64Guest - Red Hat Fedora (64-bit)
#    sles10Guest - SUSE Linux Enterprise 10 (32-bit)
#    sles10_64Guest - SUSE Linux Enterprise 10 (64-bit)
#    sles11Guest - SUSE Linux Enterprise 11 (32-bit)
#    sles11_64Guest - SUSE Linux Enterprise 11 (64-bit)
#    sles12_64Guest - SUSE Linux Enterprise 12 (64-bit)
#    slesGuest - SUSE Linux Enterprise 8/9 (32-bit)
#    sles64Guest - SUSE Linux Enterprise 8/9 (64-bit)
#    opensuseGuest - SUSE openSUSE (32-bit)
#    opensuse64Guest - SUSE openSUSE (64-bit)
#    ubuntuGuest - Ubuntu Linux (32-bit)
#    ubuntu64Guest - Ubuntu Linux (64-bit)
#    vmwarePhoton64Guest - VMware Photon OS (64-bit)
#
#
#  MacOS
#    darwin14_64Guest - Apple Mac OS X 10.10 (64-bit)
#    darwin15_64Guest - Apple Mac OS X 10.11 (64-bit)
#    darwin16_64Guest - Apple Mac OS X 10.12 (64-bit)
#    darwinGuest - Apple Mac OS X 10.5 (32-bit)
#    darwin64Guest - Apple Mac OS X 10.5 (64-bit)
#    darwin10Guest - Apple Mac OS X 10.6 (32-bit)
#    darwin10_64Guest - Apple Mac OS X 10.6 (64-bit)
#    darwin11Guest - Apple Mac OS X 10.7 (32-bit)
#    darwin11_64Guest - Apple Mac OS X 10.7 (64-bit)
#    darwin12_64Guest - Apple Mac OS X 10.8 (64-bit)
#    darwin13_64Guest - Apple Mac OS X 10.9 (64-bit)
#
#  Other
#    freebsdGuest - FreeBSD (32-bit)
#    freebsd64Guest - FreeBSD (64-bit)
#    os2Guest - IBM OS/2
#    netware5Guest - Novell NetWare 5.1
#    netware6Guest - Novell NetWare 6.x
#    solaris10Guest - Oracle Solaris 10 (32-bit)
#    solaris10_64Guest - Oracle Solaris 10 (64-bit)
#    solaris11_64Guest - Oracle Solaris 11 (64-bit)
#    otherGuest - Other (32-bit)
#    otherGuest64 - Other (64-bit)
#    openServer5Guest - SCO OpenServer 5
#    openServer6Guest - SCO OpenServer 6
#    unixWare7Guest - SCO UnixWare 7
#    eComStationGuest - Serenity Systems eComStation 1
#    eComStation2Guest - Serenity Systems eComStation 2
#    solaris8Guest - Sun Microsystems Solaris 8
#    solaris9Guest - Sun Microsystems Solaris 9
#    vmkernelGuest - VMware ESX 4.x
#    vmkernel5Guest - VMware ESXi 5.x
#    vmkernel6Guest - VMware ESXi 6.0
#    vmkernel65Guest - VMware ESXi 6.5
#
#  Windows
#    dosGuest - Microsoft MS-DOS
#    winNetBusinessGuest - Microsoft Small Business Server 2003
#    windows9Guest - Microsoft Windows 10 (32-bit)
#    windows9_64Guest - Microsoft Windows 10 (64-bit)
#    win2000AdvServGuest - Microsoft Windows 2000
#    win2000ProGuest - Microsoft Windows 2000 Professional
#    win2000ServGuest - Microsoft Windows 2000 Server
#    win31Guest - Microsoft Windows 3.1
#    windows7Guest - Microsoft Windows 7 (32-bit)
#    windows7_64Guest - Microsoft Windows 7 (64-bit)
#    windows8Guest - Microsoft Windows 8 (32-bit)
#    windows8_64Guest - Microsoft Windows 8 (64-bit)
#    win95Guest - Microsoft Windows 95
#    win98Guest - Microsoft Windows 98
#    winNTGuest - Microsoft Windows NT
#    winNetEnterpriseGuest - Microsoft Windows Server 2003 (32-bit)
#    winNetEnterprise64Guest - Microsoft Windows Server 2003 (64-bit)
#    winNetDatacenterGuest - Microsoft Windows Server 2003 Datacenter (32-bit)
#    winNetDatacenter64Guest - Microsoft Windows Server 2003 Datacenter (64-bit)
#    winNetStandardGuest - Microsoft Windows Server 2003 Standard (32-bit)
#    winNetStandard64Guest - Microsoft Windows Server 2003 Standard (64-bit)
#    winNetWebGuest - Microsoft Windows Server 2003 Web Edition (32-bit)
#    winLonghornGuest - Microsoft Windows Server 2008 (32-bit)
#    winLonghorn64Guest - Microsoft Windows Server 2008 (64-bit)
#    windows7Server64Guest - Microsoft Windows Server 2008 R2 (64-bit)
#    windows8Server64Guest - Microsoft Windows Server 2012 (64-bit)
#    windows9Server64Guest - Microsoft Windows Server 2016 (64-bit)
#    winVistaGuest - Microsoft Windows Vista (32-bit)
#    winVista64Guest - Microsoft Windows Vista (64-bit)
#    winXPProGuest - Microsoft Windows XP Professional (32-bit)
#    winXPPro64Guest - Microsoft Windows XP Professional (64-bit)
